### ISSUE TITLE
Random game crash(es) 

### ISSUE THREAD

**Issue by analtevs** [jbx5/devious-client#261]
**Describe the bug**
The game engine throws exception and eventually drops connection.  100% unresponsive.
(runelite/devious is responsive.  can interact with plugins, settings, etc)

**To Reproduce**
I'm not 100% clear on how to trigger the bug as it happens at various interactions with objects and sometimes players.
So far I've observed this bug happening at start up, in trade windows, banking, and running to a destination tile.

**Environment (please complete the following information):**
 - OS: Ubuntu
 - OpenOSRS version: 1.0.20-STABLE
 - Launcher version: 1.0.1

**Additional context**
https://pastebin.com/9yMjGiVM (full details here)

seems to throw these few exceptions:

```
ERROR net.runelite.client.RuneLite - Failure during startup
ve: null
	at oc.al(GrandExchangeOfferTotalQuantityComparator.java:104)
	at gm.av(class164.java:218)
	at gm.ab(class164.java:165)

WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.ArrayIndexOutOfBoundsException: Index 70 out of bounds for length 70
	at net.runelite.api.model.Jarvis.findLeftMost(Jarvis.java:174)
	at net.runelite.api.model.Jarvis.convexHull(Jarvis.java:114)

WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.ArrayIndexOutOfBoundsException: Index 54 out of bounds for length 54
	at net.runelite.api.model.Jarvis.findLeftMost(Jarvis.java:174)
	at net.runelite.api.model.Jarvis.convexHull(Jarvis.java:114)
	
WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
ve: null
	at oc.al(GrandExchangeOfferTotalQuantityComparator.java:104)
	at di.cg(Actor.java:239)
```

can provide more detail upon request.   since i can't trigger this on demand it may take some time to reproduce.

**Comment by analtevs** [comment]
```
java -jar devious-client-launcher.jar --nojvm --stable --world=330 --account=user:pass
```

```
[OpenOSRS] ERROR net.runelite.client.RuneLite - Failure during startup
ve: null
	at oc.al(GrandExchangeOfferTotalQuantityComparator.java:104)
	at nm.ar(Widget.java:159)
	at gp.ax(class167.java:92)
	at jq.ao(TextureProvider.java:290)
	at oa.au(Language.java:1995)
	at client.changeWorld(Client.java)
	at net.runelite.client.RuneLite.setWorld(RuneLite.java:620)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at net.runelite.client.RuneLite.start(RuneLite.java:570)
	at net.runelite.client.RuneLite.main(RuneLite.java:329)
	at net.unethicalite.client.Unethicalite.main(Unethicalite.java:65)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.runelite.launcher.ReflectionLauncher$1.run(ReflectionLauncher.java:64)

```

***java -version***
```
openjdk version "17.0.9" 2023-10-17
OpenJDK Runtime Environment (build 17.0.9+8)
OpenJDK 64-Bit Server VM (build 17.0.9+8, mixed mode)
```

**Comment by analtevs** [comment]
```java
2023-11-11 21:09:10 UTC [pool-8-thread-1] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
vf: null
	at iw.ah(CollisionMap.java:62)
	at df.cs(Actor.java:234)
	at ds.copy$getModel(Player.java:215)
	at ds.ah(Player.java:240)
	at kt.getModel(Renderable.java)
	at ds.getConvexHull(Player.java:222)
	at df.getClickPoint(Actor.java:22)
	at net.unethicalite.client.managers.interaction.InteractionManager.onMenuAutomated(InteractionManager.java:64)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:220)
	at net.runelite.client.callback.Hooks.post(Hooks.java:184)
	at client.interact(Client.java:167)
	at ds.interact(Player.java:93)
	at ds.interact(Player.java:86)
	at ds.interact(Player.java:79)
	at net.unethicalite.api.Interactable.interact(Interactable.java:114)
	at io.reisub.unethicalite.runecrafting.tasks.HandleTrade.sendTradeRequest(HandleTrade.java:125)
	at io.reisub.unethicalite.runecrafting.tasks.HandleTrade.execute(HandleTrade.java:93)
	at io.reisub.unethicalite.utils.TickScript.tick(TickScript.java:301)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

happen all the time but it happens 30% of the time over an hour+ session

**Comment by analtevs** [comment]
still can't find the source of these random crashes. probably something in the external stuff.

**Comment by abdstg** [comment]
Same with me, sometimes crash when detecting player or bank interaction
